name: GitHub Actions with AWS OIDC
run-name: ${{ github.actor }} - ${{ github.workflow }} - ${{ github.ref }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::993471332178:role/github-actions
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - id: Init
        run: terraform init
      - id: Plan
        run: terraform plan -out=tf.plan
      - id: apply
        run: terraform apply tf.plan
